export const SUPABASE_URL = 'https://ejnmfolwyugpqompofng.supabase.co'
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqbm1mb2x3eXVncHFvbXBvZm5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NTY2MzEsImV4cCI6MjA3ODAzMjYzMX0.4XaO-SDwfu-NwrG5hVxD3IlqTlJip55Suv4CSdMun8k'
